version: "3.9"
services:
  db:
    image: postgres:15
    container_name: autocheck_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: autocheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autocheck"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: